//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Driver()
        {
            this.DriverREO = new HashSet<DriverREO>();
        }
    
        public long Id { get; set; }
        public string DriverName { get; set; }
        public string mayorNumber { get; set; }
        public string Mobile { get; set; }
        public string LicenceNumber { get; set; }
        public string InteligentNumber { get; set; }
        public string DriverType { get; set; }
        public string Destination { get; set; }
        public string ImPureWeight { get; set; }
        public string PureWeight { get; set; }
        public string TruckWeight { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverREO> DriverREO { get; set; }
    }
}
