//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DriverREO
    {
        public long Id { get; set; }
        public Nullable<long> IdDriver { get; set; }
        public Nullable<long> IdREO { get; set; }
    
        public virtual Driver Driver { get; set; }
        public virtual RecordEntryExitOrder RecordEntryExitOrder { get; set; }
    }
}
