//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exitorder
    {
        public long Id { get; set; }
        public string CustomerFullName { get; set; }
        public Nullable<System.DateTime> Uploaddate { get; set; }
        public Nullable<long> IdStore { get; set; }
        public string ProductCode { get; set; }
    
        public virtual Store Store { get; set; }
    }
}
