//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GoharSangEntities : DbContext
    {
        public GoharSangEntities()
            : base("name=GoharSangEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cops> Cops { get; set; }
        public virtual DbSet<CopsBooking> CopsBooking { get; set; }
        public virtual DbSet<Driver> Driver { get; set; }
        public virtual DbSet<DriverREO> DriverREO { get; set; }
        public virtual DbSet<Exitorder> Exitorder { get; set; }
        public virtual DbSet<mine> mine { get; set; }
        public virtual DbSet<Record_the_Entrry_Image> Record_the_Entrry_Image { get; set; }
        public virtual DbSet<Record_the_entry> Record_the_entry { get; set; }
        public virtual DbSet<RecordEntryCopsBooking> RecordEntryCopsBooking { get; set; }
        public virtual DbSet<RecordEntryExitOrder> RecordEntryExitOrder { get; set; }
        public virtual DbSet<Role> Role { get; set; }
        public virtual DbSet<State> State { get; set; }
        public virtual DbSet<Store> Store { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<UserRole> UserRole { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserStoreRole> UserStoreRole { get; set; }
    }
}
