//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordEntryCopsBooking
    {
        public long Id { get; set; }
        public Nullable<long> IdCopsBooking { get; set; }
        public Nullable<long> IdRecordEntry { get; set; }
        public Nullable<bool> StateExit { get; set; }
    
        public virtual CopsBooking CopsBooking { get; set; }
        public virtual Record_the_entry Record_the_entry { get; set; }
    }
}
