//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordEntryExitOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RecordEntryExitOrder()
        {
            this.DriverREO = new HashSet<DriverREO>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdExitOrder { get; set; }
        public Nullable<long> IdRecordEntry { get; set; }
        public Nullable<bool> StateExit { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DriverREO> DriverREO { get; set; }
        public virtual Exitorder Exitorder { get; set; }
        public virtual Record_the_entry Record_the_entry { get; set; }
    }
}
