//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordEntryExitOrder
    {
        public long Id { get; set; }
        public Nullable<long> IdExitOrder { get; set; }
        public Nullable<long> IdRecordEntry { get; set; }
    
        public virtual Exitorder Exitorder { get; set; }
    }
}
