//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoharSang.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record_the_entry
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record_the_entry()
        {
            this.Record_the_Entrry_Image = new HashSet<Record_the_Entrry_Image>();
            this.RecordEntryCopsBooking = new HashSet<RecordEntryCopsBooking>();
            this.RecordEntryExitOrder = new HashSet<RecordEntryExitOrder>();
        }
    
        public long Id { get; set; }
        public Nullable<long> IdMine { get; set; }
        public Nullable<long> IdCops { get; set; }
        public string Weight { get; set; }
        public string length { get; set; }
        public string width { get; set; }
        public string Height { get; set; }
        public string CopsCod { get; set; }
        public Nullable<long> IdStore { get; set; }
        public string Transfernumber { get; set; }
        public string Trucknumber { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Time { get; set; }
        public Nullable<int> StateDelete { get; set; }
        public string basculenumber { get; set; }
        public Nullable<bool> ExitState { get; set; }
        public Nullable<bool> StateCopReserve { get; set; }
    
        public virtual Cops Cops { get; set; }
        public virtual mine mine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Record_the_Entrry_Image> Record_the_Entrry_Image { get; set; }
        public virtual Store Store { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordEntryCopsBooking> RecordEntryCopsBooking { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RecordEntryExitOrder> RecordEntryExitOrder { get; set; }
    }
}
